### ISSUE TITLE
"Get Attributes" doesn't reset

### ISSUE THREAD

**Issue by GeekThis** [FF-Plugins-Active/FF_PugiXml#2]
The `Get Attributes` node doesn't reset its result when called multiple times. 

Might be easily fixed by adding `Out_Attributes.Empty();` at the beginning of the function : 
https://github.com/FF-Plugins-Active/FF_PugiXml/blob/867413de1acf0a614a16f13ac7d14776f94e3de1/Source/FF_PugiXml/Private/FF_PugiXmlBPLibrary.cpp#L1151

**Comment by ffreality** [comment]
Yes or we can just create a new map and define it after function. fixing it right now.

**Comment by ffreality** [comment]
https://github.com/FF-Plugins-Active/FF_PugiXml/commit/97912ece6a4166eb26916c8c3d2f3d8d22d0013d

fixed, sir !
Have a good day !

btw. I updated it to 5.5
